create table users(
	ID uuid primary key,
	user_firstname varchar(50),
	user_lastname varchar(50),
	user_login varchar(60),
	user_pass varchar(255),
	user_nicename varchar(50),
	user_email varchar(100),
	user_url varchar(100),
	user_registered timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_activation_key varchar(255),
	user_status integer,
	display_name varchar(250),
	user_profstatus varchar(50), 
	user_affiliation varchar(30),
	user_expertise varchar(30), 
	user_country char(3), 
	user_age smallint, 
	user_gender char(1), 
	user_sectors varchar(11)[],
	user_projects uuid[],
	fav_articles uuid[], 
	fav_webinars uuid[]
); 